public class frases {
	private static String frase;		
	public frases (){
		String frases[]= {"-Cuanto más lees, más cosas sabrás. Cuantas más cosas aprendas, a más lugares viajaras.-Dr. Seuss.",
				"-La capacidad y gusto por la lectura da acceso a lo que ya ha sido descubierto por otros.-Abraham Lincoln.",
				"-Leer es equivalente a pensar con la cabeza de otra persona en lugar de con la propia.-Arthur Schopenhauer.",
				"-Si encontramos a un hombre de extraño intelecto, deberíamos preguntarle qué libros lee.-Ralph Waldo Emerson.",
				"-Escribe algo que merezca la pena o lee algo que merezca la pena.-Benjamin Franklin.",
				"-No importa lo ocupado que piensas que estas, debes encontrar tiempo para leer, o entregarte a una ignorancia autoelegida.-Confucio.",
				"-Un libro es un regalo que puedes abrir una y otra vez.-Garrison Keillor.",
				"-La persona que no lee buenos libros no tiene ventaja sobre el que no puede leer.-Mark Twain.",
				"-Leemos para saber que no estamos solos.-William Nicholson.",
				"-La lectura es para la mente lo que el ejercicio es para el cuerpo.-Joseph Addison.",
				"-El que ama la lectura, tiene todo a su alcance.-William Godwin.",
				"-Es lo que lees cuando no tienes que hacerlo, lo que determina lo que serás.-Oscar Wilde.",
				"-Hay más tesoros en los libros que en todo el botín de la Isla del Tesoro.-Walt Disney.",
				"-La lectura de todos los buenos libros es como una conversación con las mejores personas de los siglos pasados.-René Descartes.",
				"-Un gran libro te debe dejar con muchas experiencias, y algo agotado al final. Vives varias vidas al leer.-William Styron.",
				"-La lectura es una forma de arte y toda persona puede ser artista.-Edwin Louis Cole.",
				"-Un libro es el arma más efectiva contra la intolerancia e ignorancia.-Lyndon Baines Johnson.",
				"-Si uno no puede disfrutar leyendo un libro una y otra vez, no tiene sentido leerlo.-Oscar Wilde.",
				"-Un lector vive mil vidas antes de morir. El que nunca lee solo vive una.-George R.R. Martin.",
				"-Un hombre se conoce por los libros que lee.-Ralph Waldo Emerson.",
				"-Los libros son los amigos más silenciosos y constantes; son los consejeros más accesibles y los maestros más pacientes.-Charles William Eliot.",
				"-Los libros son espejos: solo ves en ellos lo que tienes en tu interior.-Carlos Ruiz Zafón.",
				"-La lectura es una herramienta básica para vivir una buena vida.-Joseph Addison.",
				"-No hay disfrute como la lectura.-Jane Austen.",
				"-Encuentro la educación muy educativa. Cada vez que alguien la enciende, voy a otra habitación y leo un libro.-Groucho Marx.",
				"-Una vez que aprendes a leer, serás libre para siempre.-Frederick Douglass.",
				"-Algunos libros deberían ser saboreados, otros devorados, pero solo unos pocos deberían ser mascados y digeridos.-Francis Bacon.",
				"-Aprender a leer es encender un fuego; cada sílaba pronunciada es una chispa.-Víctor Hugo.",
				"-Leamos y bailemos; estas dos diversiones no harán ningún daño al mundo.-Voltaire.",
				"-Si no te gusta leer, no has encontrado el libro correcto.-J.K. Rowling.",
				"-Hoy un lector, mañana un líder.-Logan Pearsall Smith.",
				"-Si solo lees los libros que todo el mundo esta leyendo, solo puedes pensar lo que todo el mundo esta pensando.-Haruki Murakami.",
				"-Nunca confíes en alguien que no haya traído un libro consigo.-Lemony Snicket.",
				"-Nunca dos personas leyeron el mismo libro.-Edmund Wilson.",
				"-La lectura nos da un lugar al que ir cuando tenemos que estar donde estamos.-Mason Cooley",
				"-No he conocido ningún mal que una hora de lectura no alivie.-Charles de Montesquieu",
				"-La lectura tras cierta edad desvía a la mente demasiado de sus ocupaciones creativas. Cualquier hombre que lee demasiado y usa poco su propio cerebro, cae en hábitos perezosos de pensamiento.-Albert Einstein.",
				"-Lo único importante en un libro es el significado que tiene para ti.-W. Somerset Maugham.",
				"-Un buen libro no tiene final.-R.D. Cumming.",
				"-Piensa antes de hablar. Lee antes de pensar.-Fran Lebowitz.",
				"-No tienes que quemar libros para destruir una cultura. Simplemente consigue que la gente los queme.-Ray Bradbury.",
				"-Los libros que te ayudan más son los que te hacen pensar más. La forma más dura de aprender es con la lectura, pero un gran libro de un gran pensador, es un barco de pensamientos, profundamente cargado verdad y belleza.-Pablo Neruda.",
				"-Los libros son el avión, el tren, el camino. Son el destino y el viaje. Son el hogar.-Anna Quindlen.",
				"-Sin lágrimas en el escritor, no hay lágrimas en el lector. Sin sorpresa en el escritor, no hay sorpresa en el lector.-Robert Frost.",
				"-Es bueno leer todo del algo y algo de todo.-Lord Henry P. Brougham.",
				"-Eres el mismo ahora que dentro de cinco años, excepto por las personas que has conocido y los libros que has leído.-Charlie Jones.",
				"-Lee para vivir.-Gustave Flaubert.",
				"-Un libro es un sueño que tienes en tu mano.-Neil Gaiman.",
				"-Muéstrame una familia de lectores y te mostraré la gente que mueve el mundo.-Napoleón Bonaparte.",
				"-No deberíamos enseñar los grandes libros, deberíamos enseñar el amor por la lectura.-B. F. Skinner.",
				"-Muchas personas se sienten mejor con la mera vista de un libro.-Jane Smiley.",
				"-Piensas que tu dolor es imprecedente en la historia del mundo, pero luego lees. Son los libros los que me enseñaron que las cosas que me atormentaban eran las que me conectaban con la gente viva o que había estado viva.-James Baldwin.",
				"-Las ideas transformadoras de la vida siempre me han llegado a través de los libros.-Bell Hooks.",
				"-Los libros son magia única portátil.-Stephen King.",
				"-Un libro es un dispositivo para encender la imaginación.-Alan Bennett.",
				"-No todos los lectores son líderes, pero todos los líderes son lectores.-Harry S. Truman.",
				"-Dame un hombre o mujer que ha leído mil libros y me das una compañía interesante. Dame un hombre o mujer que quizás ha leído tres libros y me das una compañía peligrosa.-Anne Rice.",
				"-Hay mucho más en un libro que solo su lectura.-Maurice Sendak.",
				"-Los libros que el mundo llama inmorales son libros que muestran al mundo sus propias vergüenzas.-Oscar Wilde.",
				"-No leas como hacen los niños, para divertirte, o como los ambiciosos, para instruirte. No, lee para vivir.-Gustave Flaubert.",
				"-La lectura proporciona a la mente materiales de conocimiento; es el pensamiento lo que hace nuestro lo que leemos.-John Locke.",
				"-La educación comienza un buen caballero, pero la lectura, la buena compañía y la reflexión deben terminarlo.-John Locke.",
				"-Un hombre solo aprende de dos maneras, una leyendo, y otra por asociación con gente más inteligente.-Will Rogers.",
				"-Los grandes libros te ayudan a entender y te ayudan a sentirte entendido.-John Green.",
				"-Dormir esta bien y los libros son mejor.-George R.R. Martin.",
				"-Hay peores crímenes que quemar libros. Uno de ellos es no leerlos.-Joseph Brodsky.",
				"-Las cosas que quieres saber están en los libros; mi mejor amigo es el que me consigue un libro que no he leído.-Abraham Lincoln.",
				"-La lectura no es más que una conversación silenciosa.-Walter Savage Landor.",
				"-No hay sustituto para los libros en la vida de un niño.-May Ellen Chase.",
				"-Leí un libro en una ocasión y toda mi vida cambió.-Orhan Pamuk.",
				"-Vivimos para los libros.-Umberto Eco.",
				"-El mayor don es una pasión por la lectura.-Elizabeth Hardwick.",
				"-Un clásico es un libro que nunca ha terminado de decir lo que tiene que decir.-Italo Calvino.",
				"-Nunca leas un libro entero por el mero hecho de haberlo comenzado.-John Witherspoon.",
				"-En un buen libro, lo mejor esta entre líneas.-Proverbio suizo.",
				"-Si me quieres contar el corazón de un hombre, no me digas lo que lee, sino lo que relee.-François Mauriac.",
				"-Lee primero los mejores libros o puede que no tengas oportunidad de leerlos.-Henry David Thoreau.",
				"-Elige un autor como eliges a un amigo.-Christopher Wren.",
				"-Los mejores libros son aquellos que te cuentan lo que ya sabes.-George Orwell.",
				"-El hábito de la lectura es el único disfrute que perdura cuando no hay otros placeres.-Anthony Trollope.",
				"-La lectura es una conversación. Todos los libros hablan. Pero un buen libro también escucha.-Mark Haddon.",
				"-Hay un arte de la lectura, al igual que un arte del pensar y un arte de la escritura.-Isaac D’Israeli.",
				"-Algunos libros nos dejan libres y otros nos hacen libres.-Ralph Waldo Emerson.",
				"-La lectura y la escritura, como todo, mejoran con la práctica.-Margaret Atwood.",
				"-Un libro es como un jardín cargado en el bolsillo.-Proverbio chino.",
				"-La lectura es un ticket de descuento a todas partes.-Mary Schmich.",
				"-La lectura te dará placer duradero.-Laura Bush.",
				"-La lectura te puede dar más satisfacción que cualquier otra cosa.-Bill Blass.",
				"-Hay muchas maneras de agrandar el mundo de tus hijos. El amor por los libros es la mejor de todas.-Jacqueline Kennedy.",
				"-Pienso en la vida como un buen libro. Cuanto más lejos llegas, más comienza a tener sentido.-Harold Kushner.",
				"-El hombre que no lee nada esta mejor educado que el que no lee nada excepto periódicos.-Thomas Jefferson.",
				"-Nunca dejes para mañana el libro que puedes leer hoy.-Holbrook Jackson.",
				"-Lee un libro y vive una vida, mira la televisión y pierde un día.",
				"-Leer un libro es aprovechar toda la experiencia que el escritor ha tenido.",
				"-Si no quieres cometer todos los errores de un escritor, lee sus libros.",
				"-La historia de la humanidad, su experiencia y todos sus conocimientos, esta grabado en los libros. Aprovéchalos y cada día serás un poco más humano.",
				"-Cuando se encuentran dos personas que han leído más de 100 libros es como si se encontrasen dos personas que han vivido más de 100 vidas.",
				"-No todos los que leen son inteligentes pero todos los inteligentes leen libros.-Lifeder.com.",
				"-Un clásico es un libro que la gente adora y no lee.-Mark Twain.",
				"-Cuando lees un buen libro, en algún lugar del mundo una puerta se abre para permitir entrar más luz.-Vera Nazarian.",
				"-Nunca leería un libro si fuera posible hablar media hora con el hombre que lo escribió.-Woodrow Wilson.",
				"-Siempre lee algo que te hará ver bien si mueres en medio de la lectura.-P.J. O’Rourke.",
				"-Los libros que no lees, no te ayudan.-Jim Rohn.",
				"-Una buena novela te dice la verdad sobre su héroe. Una mala novela te dice la verdad sobre su autor.-Gilbert K. Chesterton.",
				"-Un libro es una versión del mundo. Si no te gusta, ignóralo, u ofrece tu propia versión a cambio.-Salman Rushdie.",
				"-Sigue leyendo libros. Pero recuerda que un libro es solo un libro, y que deberás aprender a pensar por ti mismo.-Maxim Gorky.",
				"-Haz que sea una regla el hecho de nunca darle a un niño un libro que jamás leerías tú mismo.-George Bernard Shaw.",
				"-Los libros sirven para mostrarle a un hombre que sus pensamientos originales no son tan nuevos después de todo.-Abraham Lincoln.",
				"-Aquello que no sabes haría un gran libro.-Sydney Smith.",
				"-Sabes que has leído un buen libro cuando volteas la última página y sientes como si hubieses perdido un amigo.-Paul Sweeney.",
				"-Un libro es como un espejo. Si un tonto se mira en él, no puedes esperar que un genio mire de vuelta.-J. K. Rollins.",
				};
		
		this.frase=frases[(int) (Math.random()*(110))];
	}
	
	public static String getFrase() {
		return frase;
	}
}
